name: Electron Builder Action
author: Samuel Meuli
description: GitHub Action for building and releasing Electron apps

inputs:
  github_token:
    description: GitHub authentication token
    required: true
  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false