const Localization =
{
	"en": {
		Application_Loading              : "Loading",
		Application_Title                : "Taiwan Real-time Earthquake Monitoring",
		Application_Welcome              : "Welcome",
		Audio_Test                       : "Test",
		Audio_TestStop                   : "Stop",
		Setting_Dialog_Error_Title       : "Parse Error",
		Setting_Dialog_Error_Description : "Cannot parse the config file, this may be that you have accidentally deleted some important symbols such as commas, colons or quotation marks while editing, or the configuration file may have corrupted.\n\nError: {0}",
		Setting_Dialog_Reset_Title       : "Reset Settings?",
		Setting_Dialog_Reset_Description : "Are you sure that you really want to reset all settings?\nThis action is irreversible.",
		Setting_Title                    : "TREM | Settings",
		Webhook_Dialog_Error_Title       : "Webhook Error",
		Webhook_Dialog_Error_Empty       : "A valid webhook URL is needed to send a test message.",
		Webhook_Dialog_Error_Invalid     : "Invalid Webhook URL",
		Webhook_Dialog_Title             : "Webhook Test",
		Webhook_Dialog_Success           : "Test message successfully sent.\nMessage ID：{0}\nChannel ID：{1}",
	},
	"ja": {
		Application_Loading              : "ローディング中...",
		Application_Title                : "TREM 台湾リアルタイム地震モニタリング",
		Application_Welcome              : "ようこそ",
		Audio_Test                       : "音テスト",
		Audio_TestStop                   : "停止",
		Setting_Dialog_Error_Title       : "解析エラー",
		Setting_Dialog_Error_Description : "設定ファイルを解析できません。編集中にコンマ、コロン、引用符などの重要な記号を誤って削除したか、設定ファイルが破損している可能性があります。\n\nエラー：{0}",
		Setting_Dialog_Reset_Title       : "設定をリセットする？",
		Setting_Dialog_Reset_Description : "本当にすべての設定をリセットしてもよろしいですか？\nこのアクションは元に戻せません。",
		Setting_Title                    : "TREM | 設定",
		Webhook_Dialog_Error_Title       : "ウェブフックエラー",
		Webhook_Dialog_Error_Empty       : "テストメッセージを送信するには、有効な Webhook URL が必要です。",
		Webhook_Dialog_Error_Invalid     : "無效な Webhook URL",
		Webhook_Dialog_Title             : "Webhook テスト",
		Webhook_Dialog_Success           : "テストメッセージが正常に送信されました。\nメッセージ ID：{0}\nチャンネル ID：{1}",
	},
	"ru": {
		Application_Loading              : "Загрузка",
		Application_Title                : "TREM Мониторинг землетрясений на Тайване в режиме реального времени",
		Application_Welcome              : "Добро пожаловать",
		Audio_Test                       : "Тестовый звук",
		Audio_TestStop                   : "Остановить",
		Setting_Dialog_Error_Title       : "Ошибка разбора",
		Setting_Dialog_Error_Description : "Невозможно разобрать файл конфигурации, возможно, вы случайно удалили некоторые важные символы, такие как запятые, двоеточия или кавычки во время редактирования, или файл конфигурации мог быть поврежден.\n\nОшибка: {0}",
		Setting_Dialog_Reset_Title       : "Сбросить настройки?",
		Setting_Dialog_Reset_Description : "Вы уверены, что действительно хотите сбросить все настройки?\nэто действие необратимо",
		Setting_Title                    : "TREM | Настройки",
		Webhook_Dialog_Error_Title       : "Ошибка Webhook",
		Webhook_Dialog_Error_Empty       : "Для отправки тестового сообщения необходим действительный ссылка Webhook",
		Webhook_Dialog_Error_Invalid     : "Неверный ссылка Webhook",
		Webhook_Dialog_Title             : "Тест Webhook",
		Webhook_Dialog_Success           : "Тестовое сообщение успешно отправлено.\nИдентификатор сообщения：{0}\nИдентификатор канала：{1}",
	},
	"zh-TW": {
		Application_Loading              : "載入中...",
		Application_Title                : "TREM 台灣即時地震監測",
		Application_Welcome              : "歡迎",
		Audio_Test                       : "測試音效",
		Audio_TestStop                   : "停止測試",
		Setting_Dialog_Error_Title       : "設定檔錯誤",
		Setting_Dialog_Error_Description : "無法解析設定檔，這可能是你在編輯時不小心刪掉了一些重要的符號，像是逗號、冒號或引號，或是設定檔損壞。\n\n錯誤：{0}",
		Setting_Dialog_Reset_Title       : "重置設定？",
		Setting_Dialog_Reset_Description : "您確定您真的要重置所有設定嗎\n這個動作將無法挽回",
		Setting_Title                    : "TREM | 設定",
		Webhook_Dialog_Error_Title       : "Webhook 錯誤",
		Webhook_Dialog_Error_Empty       : "發送測試訊息需要有效的 Webhook 連結。",
		Webhook_Dialog_Error_Invalid     : "無效的 Webhook 連結",
		Webhook_Dialog_Title             : "Webhook 測試",
		Webhook_Dialog_Success           : "Webhook 發送測試訊息成功\n訊息ID：{0}\n頻道ID：{1}",
	},
};
