name: TREM Build

on:
  push:
    branches:
      - pre.30

jobs:
  release:
    name: build and release TREM app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dev/!(*.exe)"
          npx rimraf "dev/!(*.zip)"
          
      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "dev/!(*.dmg)"
          npx rimraf "dev/!(*.zip)"
      
      - name: Cleanup Artifacts for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          npx rimraf "dev/!(*.deb)"
          npx rimraf "dev/!(*.AppImage)"
          npx rimraf "dev/!(*.zip)"
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dev

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dev/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
